services:
  comfyui:
    container_name: comfyui
    image: ghcr.io/mitchross/comfyui-flux:cu124
    restart: unless-stopped
    ports:
      - "8188:8188"
    volumes:
      - "./data:/app"
    environment:
      - CLI_ARGS=
      - HF_TOKEN=${HF_TOKEN}
      - LOW_VRAM=${LOW_VRAM:-false}
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0']
    #           capabilities: [gpu]