name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILDKIT: 1

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        cuda_version: [cu121, cu124]
        image_type: [base, flux]
        python_version: [3.11]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cache for pip and apt
        uses: actions/cache@v4
        with:
          path: |
            /tmp/.buildx-cache
            /tmp/.buildx-cache-new
            /opt/comfyui/cache/pip
            /var/cache/apt
          key: ${{ runner.os }}-buildx-${{ matrix.cuda_version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.cuda_version }}-
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:v0.12.0
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image_type }}
          tags: |
            type=raw,value=${{ matrix.cuda_version }}
            type=raw,value=latest,enable=${{ matrix.cuda_version == 'cu121' }}
            type=semver,pattern={{version}}-${{ matrix.cuda_version }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.cuda_version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.image_type }}
          platforms: linux/amd64
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}
            PYTHON_VERSION=${{ matrix.python_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          provenance: false

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache